@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_LEFT_RIGHT()
!theme vibrant

title C4 Container - Iris Architecture

Person(user, "User", "Frontend, backend, or bot consuming indicators")
System_Boundary(iris, "Iris") {
  Container(nginx, "Nginx", "Reverse Proxy")
  Container(api, "Iris API", "C# / ASP.NET Core + Hangfire", "Restful API with scheduled jobs") {
  }
  ContainerDb(redis, "Redis", "Time Series", "Stores indicators as times series for fast retrieval")
}

Container_Ext(bacen, "Official Data Source", "BCB External API", "Source of economic indicators")

Rel(user, nginx, "HTTP(s) request")
Rel(nginx, api, "Proxies requests")
Rel(api, redis, "Reads/writes series")
Rel(api, bacen, "Fetches data")

SHOW_PERSON_OUTLINE()

@enduml